name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe what you'd like to see.
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this work?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other approaches you've thought about?
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of VidPipe does this relate to?
      options:
        - Pipeline (transcription, captions, shorts, etc.)
        - LLM Providers
        - CLI / Configuration
        - Social Media Posting
        - Documentation
        - Other
    validations:
      required: true
